- README.md
- jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/SpansToDependencyLinks.java
- jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/model/Process.java
- jaeger-spark-dependencies-test/src/main/java/io/jaegertracing/spark/dependencies/test/DependenciesTest.java
- jaeger-spark-dependencies-test/src/main/java/io/jaegertracing/spark/dependencies/test/DependencyLinkDerivator.java
- jaeger-spark-dependencies-test/src/main/java/io/jaegertracing/spark/dependencies/test/TracersGenerator.java
- jaeger-spark-dependencies-test/src/main/java/io/jaegertracing/spark/dependencies/test/tree/Node.java
- jaeger-spark-dependencies-test/src/main/java/io/jaegertracing/spark/dependencies/test/tree/TracingWrapper.java
- jaeger-spark-dependencies-test/src/main/java/io/jaegertracing/spark/dependencies/test/tree/TreeGenerator.java
Partially implements #3 
The current implementation does not handle zipkin spans correctly, specifically:
* shared RPC
* span reported in multiple fractions (e.g.span). For instance brave can report span with just one binary annotation.
Therefore it calculates wrong counts and missing links for RPC spans. However one can still use this job when using native zipkin tracers.
This is a simple fix which does its best to determine correct links without looking into tags.
The only issue which is not covered is when RPC a span is reported in a single span (with cs,cr,sr,ss annotations). This happens only if service is sending requests to itself and tracer caches spans internally.
> Support for zipkin shared spans

- README.md
- jaeger-spark-dependencies-cassandra/src/main/java/io/jaegertracing/spark/dependencies/cassandra/CassandraDependenciesJob.java
- jaeger-spark-dependencies-elasticsearch/src/main/java/io/jaegertracing/spark/dependencies/elastic/ElasticsearchDependenciesJob.java
- jaeger-spark-dependencies/src/main/resources/log4j.properties
Fixes #15 
Example output:
```
docker run  --env="STORAGE=cassandra" jaegertracing/spark-dependencies:latest | fpaste                 11:11 
17/10/10 09:11:55 INFO CassandraDependenciesJob: Running Dependencies job for 2017-10-10T00:00Z: 1507593600000000 ≤ Span.timestamp 1507679999999999
17/10/10 09:11:55 INFO SparkContext: Running Spark version 2.1.1
17/10/10 09:11:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/10/10 09:11:55 INFO SecurityManager: Changing view acls to: root
17/10/10 09:11:55 INFO SecurityManager: Changing modify acls to: root
17/10/10 09:11:55 INFO SecurityManager: Changing view acls groups to: 
17/10/10 09:11:55 INFO SecurityManager: Changing modify acls groups to: 
17/10/10 09:11:55 …
```
> Use slf4j and set logging level to INFO for jaegertracing classes

- .gitignore
- pom.xml
Yes this can be globally configured, but tools like the license checker
need to know whats ignored too, so its best to have these in-tree so the
results are consistent for everyone.
> Ignore more editor debris

- Dockerfile
- README.md
- jaeger-spark-dependencies-cassandra/src/main/java/io/jaegertracing/spark/dependencies/cassandra/CassandraDependenciesJob.java
Different version of https://github.com/jaegertracing/spark-dependencies/pull/21
The original codebase contained SSL configuration via `CASSANDRA_USE_SSL`. Trust store and pass are configured via `javax.net.ssl`, but these properties weren't passed to java command in docker.
> Enable cassandra client SSL

- README.md
- jaeger-spark-dependencies-elasticsearch/src/main/java/io/jaegertracing/spark/dependencies/elastic/ElasticsearchDependenciesJob.java
In es cluster mode, there are three node role(master,data,client).
Maybe the data node only listen in local loopback(127.0.0.1) ip, then run the job will cause error:
"
18/08/21 23:03:23 ERROR NetworkClient: Node [127.0.0.1:9201] failed (Connection refused: connect); selected next node [127.0.0.1:9210] 
18/08/21 23:03:27 ERROR NetworkClient: Node [127.0.0.1:9210] failed (Connection refused: connect); selected next node [10.1.11.123:9200] 
18/08/21 23:03:31 ERROR NetworkClient: Node [127.0.0.1:9201] failed (Connection refused: connect); no other nodes left - aborting... Exception in thread "main" org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[127.0.0.1:9201]]
"
this is cause by …
> Make ES client-node only configurable

- jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/SpansToDependencyLinks.java
- jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/model/Span.java
Resolves : https://github.com/jaegertracing/spark-dependencies/issues/49
Currently the validation of the kind of the span is done on the following
method :
* When at least one tag has client, it is considered as a client tag
* When at least one tag has server, it is considered as a server tag
This patch verify the kind by checking span.kind tag (as defined
in opentracing specification)
Signed-off-by: Etienne Carriere <etienne.a.carriere@socgen.com>
> For validating of the kind of a span, use span.kind type

- jaeger-spark-dependencies-cassandra/src/main/java/io/jaegertracing/spark/dependencies/cassandra/CassandraDependenciesJob.java
- jaeger-spark-dependencies-cassandra/src/test/java/io/jaegertracing/spark/dependencies/cassandra/CassandraDependenciesJobTest.java
- jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/model/Dependency.java
> Support dependencies v2 in c*

- jaeger-spark-dependencies-cassandra/src/main/java/io/jaegertracing/spark/dependencies/cassandra/CassandraDependenciesJob.java
- jaeger-spark-dependencies-cassandra/src/test/java/io/jaegertracing/spark/dependencies/cassandra/CassandraDependenciesJobTest.java
- jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/DependenciesSparkHelper.java
- jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/SpansToDependencyLinks.java
- jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/model/Span.java
- jaeger-spark-dependencies-elasticsearch/src/main/java/io/jaegertracing/spark/dependencies/elastic/ElasticsearchDependenciesJob.java
- jaeger-spark-dependencies-elasticsearch/src/test/java/io/jaegertracing/spark/dependencies/elastic/ElasticsearchDependenciesJobTest.java
- jaeger-spark-dependencies/src/main/java/io/jaegertracing/spark/dependencies/DependenciesSparkJob.java
Resolves : https://github.com/jaegertracing/spark-dependencies/issues/28
With the peer.service tag is present, it creates 'pseudo-service' when the span :
* is a leaf (no children)
* is a client (span.kind = 'client')
* has the tag tag_key (as specified in commandline)
The 'pseudo-service' name is the value of the tag 'peer.service'.
The tag key can be overriden by env variable
Signed-off-by: Etienne Carriere <etienne.a.carriere@socgen.com>
> Add in DAG the services called but not instrumented

- Dockerfile
- entrypoint.sh
Resolves https://github.com/jaegertracing/jaeger-operator/issues/405
OCP executes the container with random UID and spark requires that value to be present in `/etc/paswd`.
Related links: 
* https://stackoverflow.com/a/45202955/4158442
* https://stackoverflow.com/questions/41864985/hadoop-ioexception-failure-to-login
* https://github.com/radanalyticsio/openshift-spark/blob/2.4/modules/common/added/scripts/entrypoint#L50
> Add entry to passwd when missing in docker

- jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/SpansToDependencyLinks.java
- jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/model/Dependency.java
- jaeger-spark-dependencies-common/src/test/java/io/jaegertracing/spark/dependencies/SpansToDependencyLinksTest.java
Signed-off-by: Uladzislau Kiva <knijaz@gmail.com>
-Spans with tags consumer and producer should be visible at DAG and Dependencies diagrams (https://github.com/jaegertracing/jaeger-ui/issues/451)
- Additional check if SPAN_KIND_CONSUMER or SPAN_KIND_PRODUCER
> Spans for kinds "producer" and "consumer" should be resolved as a dependency

- Dockerfile
- entrypoint.sh
Created based on https://github.com/jaegertracing/spark-dependencies/pull/80
The alpine image is not maintained anymore. They have changed to `version-alpine` however it gets updates less frequently than slim version.
cc) @mindw 
The image size was 210mb and now is 291mb. 
> Use openjdk 8 slim image

- README.md
- jaeger-spark-dependencies-elasticsearch/src/main/java/io/jaegertracing/spark/dependencies/elastic/ElasticsearchDependenciesJob.java
We don't want to load the multiple GBs/day into memory a day to determine our dependency graph. Instead we are fine with an approximation based on the connections we saw in the past 2h.
Make the loaded span range configurable. Query taken from https://github.com/jaegertracing/spark-dependencies/pull/86 ❤️
> Elasticsearch: Make the span range configurable

- README.md
- jaeger-spark-dependencies-elasticsearch/src/main/java/io/jaegertracing/spark/dependencies/elastic/ElasticsearchDependenciesJob.java
Signed-off-by: Chen Zhengwei <chenzhengwei@inspur.com>
- Resolves https://github.com/jaegertracing/jaeger/issues/1489
Jaeger can customize the es date format.
- User can configure the date separator to change the date format.
- Default date formate is yyyy-MM-dd, it won't affect the old version.
Associated PR: https://github.com/jaegertracing/jaeger/pull/2637
> Add elasticsearch storage date format config.

- .github/workflows/ci.yaml
- jaeger-spark-dependencies-elasticsearch/pom.xml
Current version of elasticsearch-spark-20 jar is using a 7.x version and doesn't want to work with Elasticsearch 8.x.
- Resolves #125
- Bumping version of jar to make it also work with 8.x versions.
> Bump Elasticsearch spark version to 8.2.3

- .github/workflows/ci.yaml
Cassandra tests started failing, as diagnosed by @vlsi in https://github.com/jaegertracing/spark-dependencies/pull/142#issuecomment-2637369354
possibly related to https://github.com/jaegertracing/jaeger/pull/5922
Temporarily pin Jaeger version in the test to before that pull request.
> Pin Jaeger version in Cassandra test

- .github/workflows/ci.yaml
This removes irrelevant progress lines from the CI output:
```
Progress (1): 2.8/15 kB
Progress (1): 5.5/15 kB
Progress (1): 8.3/15 kB
Progress (1): 11/15 kB
Progress (1): 14/15 kB
Progress (1): 15 kB
```
- 
- 
> Reduce verbosity on GitHub CI

- .github/workflows/ci.yaml
- jaeger-spark-dependencies-cassandra/src/test/java/io/jaegertracing/spark/dependencies/cassandra/CassandraDependenciesJobTest.java
Current tests are failing, per https://github.com/jaegertracing/spark-dependencies/pull/142#issuecomment-2637369354
> Use Cassandra 4.1 in integration test

- Dockerfile
Previously, every docker build downloaded Maven dependencies on every build. This enables reuse .m2 folder across builds which significantly improves the build times.
Running `docker build .` takes time, and most of the time is spent on downloading Maven dependencies
Mount `/root/.m2` as a cache folder
Modify `.java` file, run `docker build .`.
After the fix, the output does not contain "downloading ..." messages.
> Сache .m2 dependencies

- .github/workflows/ci.yaml
- Dockerfile
- jaeger-spark-dependencies-cassandra/src/test/java/io/jaegertracing/spark/dependencies/cassandra/CassandraDependenciesDockerJobTest.java
- jaeger-spark-dependencies-cassandra/src/test/java/io/jaegertracing/spark/dependencies/cassandra/CassandraDependenciesJobTest.java
- jaeger-spark-dependencies-cassandra/src/test/java/io/jaegertracing/spark/dependencies/cassandra/LogToConsolePrinter.java
- jaeger-spark-dependencies/pom.xml
- pom.xml
The PR adds a test to execute the job with a docker image.
It would catch regressions if the image is not workable
> Add CassandraDependenciesDockerJobTest to verify container-based docker job execution

- .github/workflows/publish-image.yaml
- pom.xml
This change to the publication process solves two outstanding issues:
- Resolves #124
- Resolves #64
As these two issues have been outstanding for some time, I opted not to create a new issue for these changes. I am happy to rectify that if need be.
- The existing `publish-image.yml` GitHub workflow has been retooled to allow for tagged releases.
- The publication workflow now runs on two additional triggers:
- `release`: Creating a release on the GitHub repo will publish an image with a matching tag
- `workflow-dispatch`: The workflow can be run manually with an arbitrary tag string.
- Both new triggers will also update the `latest` tag, preserving the current behavior.
This change presupposes no particular release / versioning strategy - it merely provides the foundation
for adopting …
> ci(docker): Publish versioned, multiarch releases

- .github/workflows/publish-image.yaml
- Builds are broken due to the wrong driver being set at `docker build` time
- [Example build failure](https://github.com/jaegertracing/spark-dependencies/actions/runs/13777743816/job/38530254487#step:5:151)
- The `publish-image` workflow has been updated to perform an explicit `docker/setup-buildx` step, switching the build system from the `docker` driver to the `docker-container` driver, allowing multi-arch builds.
- The failure was replicated in a private repository using a minimally-edited copy of `publish-image`
- After adding the buildx step, an example multi-arch build of `alpine:latest` was observed passing.
- Example build output:
> fix(docker): Use buildx for publication builds

- jaeger-spark-dependencies-elasticsearch/src/main/java/io/jaegertracing/spark/dependencies/elastic/json/SpanDeserializer.java
Resolves https://github.com/jaegertracing/spark-dependencies/issues/157
- Handle cases where the span's `references` are null ([as is the case in Jaeger v2](https://github.com/jaegertracing/jaeger/blob/461923b41ff10964d723e8578421710d0ef42c3f/internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go#L208)) by treating it the same way as if it was an empty array (behaviour of jaeger v1)
- Built and ran locally against spans collected from a mix of jaeger v1 and v2 collectors
> Handle null references from Jaeger v2 spans in Elasticsearch
